name: Run DAG Validation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate-dag:
    name: Performs DAG validation tests
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Validate DAG
        uses: ./.github/workflows/ # Uses an action in the workflows directory
        id: hello
        with:
          github_token: ${{ secrets.github_token }}
